name: Continuous Integration

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle check
        run: ./gradlew clean check
      - name: ktlint check
        run: ./gradlew ktlintCheck